# Specific OS distribution to utilize as base image
FROM {{ os_version }}

LABEL maintainer="O1.IO"

# Create directory for storage of additional entrypoint scripts
COPY entrypoints/01-systemd-units.sh /entrypoint.d

# Include custom cmd/entrypoint for rendering and activating custom units
COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
